#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Sat Jan 17 15:46:50 2026
#

import datetime
import os
import re
import sys
from threading import Thread

import wx
from pubsub import pub as Publisher

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


WINDOW_SIZE = (700, 480)

class DebugMemoryDialog(wx.Dialog):
    column_order = ['id', 'timestamp', 'cpu', 'mem', 'file', 'resolution']
    column_headers = ['', 'Timestamp', 'CPU Time', 'Memory', 'Current file', 'Resolution']
    column_widths = [25, 100, 80, 80, 100, 90]
    def __init__(self, *args, **kwds):
        try:
            import psutil
            self.psutil_avail = True
        except ImportError:
            self.psutil_avail = False
            psutil = None

        # begin wxGlade: DebugMemoryDialog.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE | wx.DIALOG_NO_PARENT | wx.STAY_ON_TOP
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetTitle("Memory")

        self.memory_list = wx.ListCtrl(self, wx.ID_ANY, style=wx.LC_HRULES | wx.LC_REPORT | wx.LC_VRULES)
        for i in range(len(DebugMemoryDialog.column_headers)):
            self.memory_list.InsertColumn(i, DebugMemoryDialog.column_headers[i])
            self.memory_list.SetColumnWidth(i, DebugMemoryDialog.column_widths[i])

        self.snapshot_btn = wx.Button(self, wx.ID_ANY, "Take Snapshot")
        self.gc_btn = wx.Button(self, wx.ID_ANY, "Invoke Garbage Collection")
        self.button_CLOSE = wx.Button(self, wx.ID_CLOSE, "")
        self.__do_layout()

        self.Layout()
        # end wxGlade

        bestsize = self.GetBestSize()
        self.SetSize(max(bestsize[0], WINDOW_SIZE[0]), max(bestsize[1], WINDOW_SIZE[1]))
        self.Centre()

        self.Bind(wx.EVT_BUTTON, self.on_close_click, self.button_CLOSE)
        self.Bind(wx.EVT_BUTTON, self.on_snapshot_click, self.snapshot_btn)
        self.Bind(wx.EVT_BUTTON, self.on_gc_click, self.gc_btn)

        #Image loading events. Listen to these to scrape some data for the currently displayed image
        #(Which is what's going to eat up most memory...)
        self.img_resolution = ''
        self.img_filename = ''
        Publisher.subscribe(self.on_image_opened, 'container.image.opened')
        Publisher.subscribe(self.on_image_loaded, 'canvas.image.loaded')

        #Placeholder for the first entry, which is special. This one will automatically update.
        #Below it are the snapshots, copied from the top entry.
        placeholder = {
            'id': 0,
            'timestamp': 'Now',
            'cpu': '',
            'mem': '',
            'file': '',
            'resolution': '',
        }
        if not self.psutil_avail:
            #Not worth trying to do this properly.
            placeholder['timestamp'] = 'This page requires psutil installed'
            self.memory_list.SetColumnWidth(1, 500)
        self.add_list_item(placeholder)
        self.update_list_item(placeholder)

        #Continually check for memory usage on a timer and update the listctrl to show current stats
        #This shouldn't continually run while the dialog is closed, but figure that out later.
        if self.psutil_avail:
            self.timer = wx.Timer(self)
            self.Bind(wx.EVT_TIMER, self.on_timer, self.timer)
            self.timer.Start(1000)

    def __do_layout(self):
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(self.memory_list, 1, wx.EXPAND, 0)

        btn_sizer = wx.BoxSizer(wx.HORIZONTAL)
        btn_sizer.Add(self.snapshot_btn, 0, 0, 0)
        btn_sizer.Add(self.gc_btn, 0, 0, 0)
        sizer_1.Add(btn_sizer)

        sizer_2 = wx.StdDialogButtonSizer()
        sizer_1.Add(sizer_2, 0, wx.ALIGN_RIGHT | wx.ALL, 4)

        sizer_2.AddButton(self.button_CLOSE)
        sizer_2.Realize()

        self.SetSizer(sizer_1)
        self.SetEscapeId(self.button_CLOSE.GetId())

    def add_list_item(self, entry):
        """ Add an entry to the actual list control.
        Modifies the entry object to include the id; use this for future requests
        """
        index = self.memory_list.InsertItem(self.memory_list.GetItemCount(), '-')
        self.memory_list.SetItemData(index, index)  #Must be an int.
        entry['id'] = index
    def update_list_item(self, entry):
        """ Update the list control with the new values.
        """
        #entry['id'] is the unsorted row number. Sorting will change this.
        index = entry['id']
        for i in range(len(DebugMemoryDialog.column_order)):
            key = DebugMemoryDialog.column_order[i]
            self.memory_list.SetItem(index, i, str(entry[key]))

    def get_memory_details(self):
        import psutil
        pid = os.getpid()
        proc = psutil.Process(pid)
        cpu_times = proc.cpu_times()
        cpu = cpu_times.user + cpu_times.system
        mem_info = proc.memory_full_info()
        mem = round(mem_info.rss / (1024*1024), 1)

        return {
            'id': 0,
            'timestamp': datetime.datetime.now().strftime('%H:%M:%S'),
            'cpu': self.format_timestamp(cpu),
            'mem': f'{mem}mb',
            'file': self.img_filename,
            'resolution': self.img_resolution,
        }

    @staticmethod
    def format_timestamp(s: float):
        d = datetime.timedelta(seconds=s)
        ret = str(d)
        #Cleanup. '0:00:12.34500' -> '12.3'. lstrip won't work once this hits days of CPU time, but that's not very likely.
        ret = re.sub(r'\.(\d)\d+$', r'.\1', ret)
        return ret.lstrip('0:')

    def on_timer(self, event):
        usage = self.get_memory_details()
        wx.CallAfter(self.update_list_item, usage)

    def on_snapshot_click(self, event):
        """Copy the current data in the top grid row to a new entry. This will persist for the duration of the application."""
        entry = {DebugMemoryDialog.column_order[i]: self.memory_list.GetItemText(0, i) for i in range(len(DebugMemoryDialog.column_order))}
        self.add_list_item(entry)
        self.update_list_item(entry)

    def on_gc_click(self, event):
        import gc
        gc.collect()

    def on_close_click(self, event): # wxGlade: DebugDialog.<event_handler>
        #This window needs to always be alive; don't destroy it.
        self.Hide()

    def on_image_loaded(self, *, img):
        """ This includes the img itself, and thus the resolution."""
        width = img.original_width
        height = img.original_height
        self.img_resolution = f'{width}x{height}'
    def on_image_opened(self, *, item):
        """ This includes the filename. """
        self.img_filename = item.name


# end of class DebugMemoryDialog

if __name__ == '__main__':
    app = wx.App(False)
    dlg = DebugMemoryDialog(None)
    dlg.ShowModal()
